apiVersion: v1
kind: Service
metadata:
  labels:
    app: webui
  name: webui
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30036
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: webui
  sessionAffinity: None
  type: LoadBalancer
