apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  generation: 1
  labels:
    app: worker
  name: worker
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: worker
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - image: maythee/worker:v0.1
        imagePullPolicy: IfNotPresent
        name: worker
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
