apiVersion: v1
kind: Service
metadata:
  labels:
    app: adder
  name: adder
  namespace: default
  resourceVersion: "2663"
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 31204
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: adder
  sessionAffinity: None
  type: LoadBalancer
