apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: team21-client
  name: team21-client
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: team21-client
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: team21-client
    spec:
      containers:
      - image: maythee/team21-client
        imagePullPolicy: Always
        name: team21-client
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
